# Generated by Django 3.1.4 on 2020-12-20 13:23

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20201213_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-pubdate'], 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='first_name+last_name', unique=True),
        ),
        migrations.AddField(
            model_name='track',
            name='pubdate',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
