# Generated by Django 3.1.4 on 2020-12-20 14:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20201220_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default='...', max_length=10000),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='last_name', unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='pubdate',
            field=models.DateTimeField(auto_created=True, editable=False, null=True),
        ),
    ]
