# Generated by Django 3.1.4 on 2020-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_auto_20201222_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
